tomchavakis/nuget-license

src/Methods.cs
Before execution would fail if old project file format was used with references in packages.config file.
This adds support for that as well, references will be listed correctly.
=> Add support for packages.config references

src/Methods.cs
Currently if t here are more projects in directory, for each project references of previous projects will be reprinted. This pull requests fixes that, it only displays references of current project.
=> Remove duplicated tables when printing references

src/InvalidLicensesException.cs, src/Methods.cs, src/Model/IValidationResult.cs, src/Model/ValidationResult.cs, src/NugetUtility.csproj, src/Program.cs, tests/NugetUtility.Tests/InvalidLicenseTests.cs, tests/NugetUtility.Tests/ProgramTests.cs
We needed to do validation against the mapped information in another project, so I added it but also left the old way.
=> added ability to validate mapped library info

README.md, src/Methods.cs, src/PackageOptions.cs
#31 Added an option to include transitive packages, that are retrieved distinctly per found project.
=> Add option to include transitive packages

src/Methods.cs
When the Folder to which the output files should be put to does not exist - create it.
=> Create output directory if it does not yet exist

src/LicenseToUrlMappings.cs, src/Methods.cs
This leads to the following:
- Validation will fail for packages that are not found
- If validation is skipped, they properly appear in the list of used packages
=> When a package cannot be found on nuget.org - add dummy license specification.

src/Methods.cs
Package reference version can be specified not only with xml-attributes like this ;
```xml
<ItemGroup>
<PackageReference Include="NugetPackage" Version="2.5.4" />
</ItemGroup>
```
.. but also with version child-element like this ;
```xml
<ItemGroup>
<PackageReference Include="NugetPackage">
<Version>2.5.4</Version>
</PackageReference>
</ItemGroup>
```
This PR fallbacks to try version-element if no version-attribute is found and should handle both scenarioes.
=> Handle PackageReference::Version also as separate element

README.md, src/Methods.cs, src/NugetUtility.csproj, src/PackageOptions.cs, tests/NugetUtility.Tests/MethodsTests.cs, tests/NugetUtility.Tests/PackageOptionsTests.cs
It seems that this project uses license for [both the verb and the noum](https://www.grammarly.com/blog/licence-license/) and these places were just typos.
I noticed this when I generated both the JSON and TXT files and they were spelled differently.
=> Fix typos s/licence/license/

README.md, src/Methods.cs, src/Program.cs, tests/NugetUtility.Tests/MethodsTests.cs
Using array of project extensions instead of a single string.
=> F# support (*.fsproj)

src/LicenseToUrlMappings.cs, src/Methods.cs, src/PackageNameAndVersion.cs, tests/NugetUtility.Tests/MethodsTests.cs
According to: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning a nuget package may specify a range of dependent versions that are compatible. This Pull Request tries to account for this by checking the licenses of the lowest and the highest explicitely specified package. 
There is a shortcoming with this approach, as exclusive specifications are not handled correctly. I think the best bet would be to let nuget resolve all packages and then use the resolved packages for license checking. Unfortunately I do not have any idea on how to acheive this.
This PR is the best I can come up with.
=> Try to handle Package Versionings of all kinds

.github/workflows/action.yml, .github/workflows/release.yml, src/NugetUtility.csproj, tests/NugetUtility.Tests/NugetUtility.Tests.csproj
Added .NET 5.0 support to execute tool inside mcr.microsoft.com/dotnet/sdk:5.0* docker build images.
@tomchavakis: please fix github workflows to add .NET 5.0 sdk during build process
=> Add .NET 5.0 support

README.md, src/LicenseToUrlMappings.cs, src/Methods.cs, src/Model/Package.cs, src/NugetUtility.csproj, src/PackageOptions.cs, tests/NugetUtility.Tests/MethodsTests.cs
Add option (default 'false') to ignore HttpClient SSL certificate errors when contacting nuget.org
=> Ignore ssl errors on HttpClient

README.md, src/Methods.cs, src/PackageOptions.cs, src/Program.cs, tests/NugetUtility.Tests/MethodsTests.cs
This addresses #29 by bypassing csproj file parsing and using the _project.assets.json_ file generated by nuget/dotnet restore.
* Adds `--use-project-assets-json`
* Fails if this is used without `-t` since the assets file includes all transitive refs. There might be a way to parse only immediate refs from the assets file, but I haven't looked into it. This is why I made this as a separate cmd line option rather than making it the default behavior.
* This option bypasses the .csproj parsing if any refs are found in the assets file.
=> Added --use-project-assets-json

README.md, src/Methods.cs, src/PackageOptions.cs, src/Program.cs, tests/NugetUtility.Tests/MethodsTests.cs, tests/NugetUtility.Tests/ProgramTests.cs
We had issues with slow runners that causes HttpClient timeouts.
By introducing the timeout option, this issue would be solved.
=> Added --timeout

src/Methods.cs
Adding Visual Basic Project File as supported file extension
Tested and working with own sample .NET Framework project file in VB
=> Adding Visual Basic Project File (.vbproj) as supported file extension

src/Methods.cs
Sorry! 😐 Somehow my old PR worked in debug for me but not anymore in stable v2.3.8.
Maybe there can be tests for this in the future, but I have no idea about that.
I missed this part here in GetValidProjects. Now it should work with .vbproj projects.
I will report back if it is working after merge. Merry Christmas 🙂
=> make .vbproj a valid project

README.md, src/Methods.cs, src/PackageOptions.cs
In order to make API requests successful in working environments with proxy configurations, it is necessary to use the system proxy in HttpClient. 
The flag `--default-proxy` is added. When used, the system proxy is applied for every http request.
Implemented using https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpclient.defaultproxy
=> adding --default-proxy flag to use the system proxy

src/Methods.cs, src/Model/LibraryInfo.cs
We (our project) need to check the git repositories for licenses that override whatever nuget says. This adds the repository information to the json output format.
=> Add repository information to JSON output.

.github/workflows/release.yml, src/NuGetUtility/NuGetUtility.csproj
This PR specifies the license of the project in the project file. This in turn leads to proper license information to be found about the project.
=> specify license in project file

src/NuGetUtility/AppLifetime.cs, src/NuGetUtility/NuGetUtility.csproj, src/NuGetUtility/Program.cs, src/NuGetUtility/ReferencedPackagesReader/ProjectsCollector.cs, src/NuGetUtility/Wrapper/MsBuildWrapper/IMsBuildAbstraction.cs, src/NuGetUtility/Wrapper/MsBuildWrapper/MsBuildAbstraction.cs, tests/NuGetUtility.Test/NuGetUtility.Test.csproj, tests/NuGetUtility.Test/ReferencedPackagesReader/ProjectsCollectorTest.cs, tests/NuGetUtility.Test/ReferencedPackagesReader/ReferencedPackagesReaderIntegrationTest.cs, tests/targets/ProjectWithTransitiveNuget/ProjectWithTransitiveNuget.csproj
This PR adds the capability to specify a solution file as input to the version 3.0.0 of the application. Further this PR alos allows for the input json file to contain solution files, project files or a combination of these.
=> Implement the possibility to specify solution files as input to the application

tests/NuGetUtility.Test/Architecture/ArchitectureTest.cs, tests/NuGetUtility.Test/Architecture/ConditionsExtensions.cs, tests/NuGetUtility.Test/Architecture/Rules/NugetAbstractionTest.cs, tests/NuGetUtility.Test/NuGetUtility.Test.csproj
As suggested in [this comment](https://github.com/tomchavakis/nuget-license/pull/154#issuecomment-1311504630), here's a simple example of an architecture test.
=> add first architecture test to codify architecture rules

src/NuGetUtility/Wrapper/MsBuildWrapper/MsBuildAbstraction.cs, tests/NuGetUtility.Test/ReferencedPackagesReader/ProjectsCollectorTest.cs, tests/targets/Projects.sln
without it, this error is thrown for relative paths
MSB0001: Internal MSBuild Error: ../../../../targets/Projects.sln unexpectedly not a rooted path
=> fix relative path to solution file throws error

src/NuGetUtility/Wrapper/NuGetWrapper/Protocol/GlobalPackagesFolderUtility.cs
This is broken in alpha because SemanticVersion.ToString and WrappedNuGetVersion.ToString behaves differently when there revision part is zero, version x.x.x.0.
=> Fix getting from global folder

Dockerfile
When following the README instructions to build the Docker image locally, I was getting the following error:
```Dockerfile
> [build-env 4/6] RUN dotnet restore:
#11 1.265   Determining projects to restore...
#11 1.694 /usr/share/dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/src/NugetUtility.csproj]
------
executor failed running [/bin/sh -c dotnet restore]: exit code: 1
```
I confirm that the image builds and runs correctly in this version which makes sense as the code supports 7.0 as per https://github.com/tomchavakis/nuget-license/pull/177
=> Update Dockerfile to .net 7.0

src/Methods.cs, tests/NugetUtility.Tests/MethodsTests.cs, tests/NugetUtility.Tests/TestProjectFiles/PackageRangeReference.csproj
Fixed issue when package version is range, e.g. [6.2.*,) . Also, fixd NullReferenceException issue when packages doesn't exists in local cache.
=> Fixed issue when package version is range, e.g. [6.2.*,)

src/Methods.cs, tests/NugetUtility.Tests/MoqMethodTests.cs, tests/NugetUtility.Tests/NugetUtility.Tests.csproj
This PR is related with the following issue:
https://github.com/tomchavakis/nuget-license/issues/182
=> fix Timeout - Task Cancelled Exception

src/HtmlPrinter.cs, src/Methods.cs, src/PackageOptions.cs
I added an HtmlPrinter class that prints an HtmlDocument to a text file of a user-configurable page width.  It has basic support for lists and a few other elements common in license documents.  Notably, there's no table support, but I think this still represents an improvement over htmlDocument.InnerText.
I also added a StripHtml method to clean up HTML from known sites with headers and footers we don't want in the text output.
Pardon the confusing branch name, btw.  Just realized I got it backwards.
=> Improved html to text

README.md, src/Methods.cs
=> also evaluate licenses in Directory.Build.props
